# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_silomesh', [dirname(__file__)])
        except ImportError:
            import _silomesh
            return _silomesh
        if fp is not None:
            try:
                _mod = imp.load_module('_silomesh', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _silomesh = swig_import_helper()
    del swig_import_helper
else:
    import _silomesh
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def init_silo(*args):
  return _silomesh.init_silo(*args)
init_silo = _silomesh.init_silo

def init_mesh(*args):
  return _silomesh.init_mesh(*args)
init_mesh = _silomesh.init_mesh

def init_var(*args):
  return _silomesh.init_var(*args)
init_var = _silomesh.init_var

def set_value(*args):
  return _silomesh.set_value(*args)
set_value = _silomesh.set_value

def finalize_var():
  return _silomesh.finalize_var()
finalize_var = _silomesh.finalize_var

def finalize_mesh():
  return _silomesh.finalize_mesh()
finalize_mesh = _silomesh.finalize_mesh

def finalize_silo():
  return _silomesh.finalize_silo()
finalize_silo = _silomesh.finalize_silo


